"""Phase 4 — edge / negative / boundary cases (TEST-PLAN.md): duplicate
slug on article create, missing required fields, malformed JSON body,
pagination offset past the end of the result set.
"""
import pytest
from django.db.utils import IntegrityError

from conduit.apps.core.tests.factories import ArticleFactory


@pytest.mark.django_db
class TestArticleCreateEdgeCases:
    def test_KNOWN_BUG_duplicate_explicit_slug_causes_unhandled_500(
        self, auth_client
    ):
        # Not one of the two quirks flagged in CONTEXT.md/TEST-PLAN.md --
        # a new discovery from writing this exact Phase 4 test case
        # ("duplicate slug on article create"). ArticleSerializer.slug is
        # manually declared (`serializers.SlugField(required=False)`,
        # conduit/apps/articles/serializers.py:12) rather than
        # auto-generated by ModelSerializer, which is what normally wires
        # up the automatic UniqueValidator DRF adds for `unique=True` model
        # fields. Without it, a client-supplied duplicate slug sails
        # through validation and hits the DB's UNIQUE constraint directly,
        # which Article.objects.create() doesn't catch -- an unhandled
        # IntegrityError, not a clean 400. Characterized as current
        # behavior per this session's general discipline (don't silently
        # patch app source); not fixed here.
        #
        # Django 1.10's test Client always re-raises a view's uncaught
        # exception rather than returning a 500 response (the
        # `raise_request_exception=False` opt-out wasn't added until a
        # later Django version) -- so the honest way to characterize this
        # here is catching the IntegrityError directly, not asserting on a
        # response status code. A real WSGI deployment with DEBUG=True
        # would show Django's debug error page with a 500 status; with
        # DEBUG=False it would be a bare 500.
        ArticleFactory(slug='taken-slug')

        with pytest.raises(IntegrityError):
            auth_client.post('/api/articles', {
                'article': {
                    'title': 'Different Title',
                    'description': 'Desc',
                    'body': 'Body',
                    'slug': 'taken-slug',
                }
            }, format='json')

    def test_missing_body_returns_400(self, auth_client):
        response = auth_client.post('/api/articles', {
            'article': {'title': 'A Title', 'description': 'Desc'}
        }, format='json')
        assert response.status_code == 400

    def test_malformed_json_body_returns_400(self, auth_client):
        response = auth_client.post(
            '/api/articles', data='{not valid json',
            content_type='application/json'
        )
        assert response.status_code == 400

    def test_no_slug_provided_gets_one_generated(self, auth_client):
        # Confirms the pre_save signal (conduit/apps/articles/signals.py)
        # actually fires end-to-end through the API, not just at the model
        # layer.
        response = auth_client.post('/api/articles', {
            'article': {
                'title': 'A Generated Slug Article',
                'description': 'Desc', 'body': 'Body',
            }
        }, format='json')

        assert response.status_code == 201
        assert response.json()['article']['slug'].startswith(
            'a-generated-slug-article-'
        )


@pytest.mark.django_db
class TestArticleListPaginationEdgeCases:
    def test_offset_past_end_of_result_set_returns_empty_list(self, api_client):
        ArticleFactory.create_batch(3)

        response = api_client.get('/api/articles?limit=20&offset=100')

        assert response.status_code == 200
        body = response.json()
        assert body['articles'] == []
        assert body['articlesCount'] == 3

    def test_list_with_no_articles_returns_empty_list_not_error(self, api_client):
        response = api_client.get('/api/articles')

        assert response.status_code == 200
        body = response.json()
        assert body['articles'] == []
        assert body['articlesCount'] == 0

    def test_negative_offset_does_not_error(self, api_client):
        ArticleFactory.create_batch(2)

        response = api_client.get('/api/articles?offset=-5')

        assert response.status_code == 200
